<Project Sdk="Microsoft.NET.Sdk">
    <Import Project="../Common.props"/>

    <PropertyGroup>
        <LangVersion>default</LangVersion>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="AutoMapper" Version="12.0.1"/>
        <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.1"/>
        <PackageReference Include="ConfigureAwait.Fody" Version="3.3.2">
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="Fody" Version="6.8.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.Extensions.Options" Version="8.0.1"/>
        <PackageReference Include="MediatR" Version="12.2.0"/>
        <PackageReference Include="FluentValidation" Version="11.9.0"/>
        <PackageReference Include="Net.Codecrete.QrCodeGenerator" Version="2.0.4"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.1"/>
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.0"/>
        <PackageReference Include="SkiaSharp" Version="2.88.7"/>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="8.0.0"/>
        <PackageReference Include="Microsoft.AspNetCore.Components.Analyzers" Version="8.0.1"/>
        <PackageReference Include="Nerdbank.GitVersioning" Version="3.6.133"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\PokerTime.Domain\PokerTime.Domain.csproj"/>
        <ProjectReference Include="..\PokerTime.Common\PokerTime.Common.csproj"/>
    </ItemGroup>
</Project>
