<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="../Common.props" />

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <LangVersion>default</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PokerTime.Application\PokerTime.Application.csproj" />
    <ProjectReference Include="..\PokerTime.Common\PokerTime.Common.csproj" />
  </ItemGroup>
</Project>
